import React from "react";
import Head from "next/head";
import Link from "next/link";

const Layout = ({ children, title, favorite }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-slate-900 py-5 mb-10">
        <Link href="/">
          <a>
            <h1 className="text-6xl text-center text-amber-400">{title}</h1>
          </a>
        </Link>
        <Link href="/favorites">
          <a>
            <h1 className="text-xl mx-24 text-right text-amber-400">
              {favorite}
            </h1>
          </a>
        </Link>
      </header>

      <main className="container mx-auto mb-5">{children}</main>
    </div>
  );
};

export default Layout;
